[project]
name = "massimal-machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pytest>=9.0.2",
    "scikit-image>=0.25.2",
    "spectral>=0.24",
    "tensorflow>=2.20.0",
]
